// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8iKM0f6h2Tgivoc_97UUhBPhfnDXZHZQ',
    appId: '1:847688702354:android:4d8df0bfbf8653ffc1494b',
    messagingSenderId: '847688702354',
    projectId: 'staffora-project-2025',
    storageBucket: 'staffora-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPa94OfN-Y2xC4eW94DqwWMO4Kj3nALNs',
    appId: '1:847688702354:ios:092a0ba4d512ca95c1494b',
    messagingSenderId: '847688702354',
    projectId: 'staffora-project-2025',
    storageBucket: 'staffora-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.staffora',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRutSuezynDOQ0LRsY8FOGmPpLQZ_7aY',
    appId: '1:847688702354:web:6f9cbafa55f01efcc1494b',
    messagingSenderId: '847688702354',
    projectId: 'staffora-project-2025',
    authDomain: 'staffora-project-2025.firebaseapp.com',
    storageBucket: 'staffora-project-2025.firebasestorage.app',
  );

}